# project title 
# student course , enrolment management system
# business problem : in a traning institute the data is in excell file, as the number of students increasing manuallu analaysing/tracking the data is difficult*/
/* Objective:
we need a system tacks the students details , courses, enrollment, instructures which is easy to track the details*/

CREATE database SQLPROJECT;
USE SQLPROJECT;
CREATE TABLE students(student_id INT primary KEY,
studentName varchar(20),
Gender varchar(20),
Age int,
City varchar(20),
Email varchar(20),
phone varchar(20),
JoiningDate date);
select * from students;

CREATE TABLE instructors(instructorID int primary key,
instructorsName varchar(20),
Department varchar (20),
experience int);	
select * from instructors;

CREATE table courses(CourseID int primary key,
CourseName varchar (20),
DurationMonths int,
Fee decimal(10,2),
instructorID int,
foreign key (instructorsID)
references instructors(instructorsID)
select * from courses;



CREATE table enrollments (EnrollmentID int primary key,
StudentsID int,
CourseID int,
EnrollmentDate Date,
ComletionStatus varchar(20),
Marks int,
foreign key (StudentsID)
References students(student_id),
Foreign key (CourseID)
References Courses(CourseId));
select * from enrollments;



# business Analyzing questions
# total number of students 
 
 select count(*) as total_students
 from students;
 
 # insights:
 # there are total 100 students in the institute 
 
 # total number of courses
  select count(*) as total_courses
  from courses;
  
  # insights:
  # there are total 5 courses in the institute 
  
  # total number of instructors 
  select count(*) total_instructors
  from instructors;
  
  # insights :
  # there are total 5 instructors
  
  # courses with fee greater then 5000
  select count(*) from courses
  where Fee>5000;
  
  # for python,power Bi, and data analytics courses fee is more than 5000
  
  # students enrolled in each course 
  
  select
  
  c.CourseName,
  count(e.EnrollmentID) as total_students
  
  from Courses as c
  join enrollments e 
  on c.courseid=e.courseid
  group by c.coursename;
  
  # most of the students are enrolled in data analytics 
  
  # Q list the students with their courses 
  select s.studentname,
  c.coursename
  from students s
  join enrollments e
  join courses c
  on e.courseid = c.courseid;

  
  
  # Q students who completed their course 
  select s.studentname,
  c.coursename,
  e.Comletionstatus
  from students s
  join enrollments e
  on s.student_id = e.StudentsID
  join courses c
  on c.courseid = e.courseid
  where e.Comletionstatus = "completed";
  
  
  # Q students who are still studing
  select s.studentname,
  c.coursename,
  e.Comletionstatus
  from students s
  join enrollments e
  on s.student_id = e.StudentsID
  join courses c
  on c.courseid = e.courseid
  where e.Comletionstatus = "Ongoing";
  
  # city wise students count 
  
  select city,count(*) as total_students
  from students
  group by city;

# insights:
# using SQl query i have analyzed that most of the students are from hyderabad

#Q revenue generated by each course
select c.coursename,
count(e.StudentsID) * c.fee as revenue
from enrollments e
join courses c
on e.courseid = c.courseid
group by c.coursename, c.fee;

# insight"
# highest revenue is generated from data analytics 
# and least revenue is generated from the course exist 


# 